### ISSUE TITLE
Build failure on Mac OS X 10.10

### ISSUE THREAD

**Issue by oubiwann** [tomszilagyi/gen_serial#1]
Hey there,

I was hoping to use gen_serial tonight, but ran across this issue:

```
$ ./make.sh
cc -Wall -O2 -g -ggdb -c -o posix_main.o posix_main.c
posix_main.c:84:30: error: use of undeclared identifier 'B460800'
        case 460800: tio.c_cflag |= B460800; break;
                                    ^
posix_main.c:85:30: error: use of undeclared identifier 'B500000'
        case 500000: tio.c_cflag |= B500000; break;
                                    ^
posix_main.c:86:30: error: use of undeclared identifier 'B576000'
        case 576000: tio.c_cflag |= B576000; break;
                                    ^
posix_main.c:87:30: error: use of undeclared identifier 'B921600'
        case 921600: tio.c_cflag |= B921600; break;
                                    ^
posix_main.c:88:31: error: use of undeclared identifier 'B1000000'
        case 1000000: tio.c_cflag |= B1000000; break;
                                     ^
posix_main.c:89:31: error: use of undeclared identifier 'B1152000'
        case 1152000: tio.c_cflag |= B1152000; break;
                                     ^
posix_main.c:90:31: error: use of undeclared identifier 'B1500000'
        case 1500000: tio.c_cflag |= B1500000; break;
                                     ^
posix_main.c:91:31: error: use of undeclared identifier 'B2000000'
        case 2000000: tio.c_cflag |= B2000000; break;
                                     ^
posix_main.c:92:31: error: use of undeclared identifier 'B2500000'
        case 2500000: tio.c_cflag |= B2500000; break;
                                     ^
posix_main.c:93:31: error: use of undeclared identifier 'B3000000'
        case 3000000: tio.c_cflag |= B3000000; break;
                                     ^
posix_main.c:94:31: error: use of undeclared identifier 'B3500000'
        case 3500000: tio.c_cflag |= B3500000; break;
                                     ^
posix_main.c:95:31: error: use of undeclared identifier 'B4000000'
        case 4000000: tio.c_cflag |= B4000000; break;
                                     ^
12 errors generated.
make: *** [posix_main.o] Error 1
```

OS Version: 10.10.1
Erlang version: 17.5

(fwiw, also fails on 17.4 and R15 ... but it's not even getting to the Erlang, so that doesn't really mean anything.)

I suspect there are missing header files (on my system -- perhaps an implicit dep?) or missing includes?

Not a C hacker, so I'm not sure how to debug further ...

**Comment by oubiwann** [comment]
Some googling:
 * Similar issue on another project here:: https://github.com/ynezz/librs232/issues/6
 * Someone stated that Mac termios lib does not have all baud rates constants definitions (http://forum.biicode.com/t/error-using-david-serial-cpp-serial-h/126/3) and that they need to be added

**Comment by tomszilagyi** [comment]
Oh well, it seems OSX does not support the same baudrate constants as Linux. (It might be that only the subset supported by OSX is standardized, I haven't checked.)

The easy solution is to just get rid of the problematic cases in the switch statement. See trivial patch below. The not-so-trivial solution is to research the issue a bit further and come up with a nicer looking OS-dependent solution to the same effect (pull requests welcome).

--- 8< ---

diff --git a/c_src/posix/posix_main.c b/c_src/posix/posix_main.c
index b9345c3..bc6c4b1 100644
--- a/c_src/posix/posix_main.c
+++ b/c_src/posix/posix_main.c
@@ -81,6 +81,7 @@ int serial_configure(struct serial_channel *_chan, struct serial_cfg *cfg)
        case 57600: tio.c_cflag |= B57600; break;
        case 115200: tio.c_cflag |= B115200; break;
        case 230400: tio.c_cflag |= B230400; break;
+#if 0
        case 460800: tio.c_cflag |= B460800; break;
        case 500000: tio.c_cflag |= B500000; break;
        case 576000: tio.c_cflag |= B576000; break;
@@ -93,6 +94,7 @@ int serial_configure(struct serial_channel *_chan, struct serial_cfg *cfg)
        case 3000000: tio.c_cflag |= B3000000; break;
        case 3500000: tio.c_cflag |= B3500000; break;
        case 4000000: tio.c_cflag |= B4000000; break;
+#endif
        default: chan->lastError = EINVAL; return -1;
        }

**Comment by tomszilagyi** [comment]
This is now fixed.
