### ISSUE TITLE
Segfault on EACCESS (posix)

### ISSUE THREAD

**Issue by lafka** [tomszilagyi/gen_serial#4]
On posix when trying to open a serial port when lacking permissions `serial_esock` segfaults.

Expected result would be to terminate the program with a exit code set to errno, something like https://github.com/tomszilagyi/gen_serial/compare/master...lafka:lafka-port-segfault?expand=1

No clue about C so let me know if there are better solutions

**Comment by lafka** [comment]
Seems to be a different issue on my side.

**Comment by tomszilagyi** [comment]
Are you using the latest master? I fixed something similar in commit fe1fae5c58026dd0b230aff0f88caf0225e22c74 but I haven't made a new release since then.

**Comment by lafka** [comment]
Missed that commit, it fixes the issue.

Would it be an idea to return the errno code to the port? it's useful to know why the port couldn't be opened.

**Comment by tomszilagyi** [comment]
I'm not really working on this anymore, so all I can say is, pull-requests are welcome :)
